version: '3.8'

services:
  msitem:
    image: emerlopes95/ms-item
    container_name: ms-item
    ports:
      - "8082:8082"
    networks:
      - bridge-ecommerce

  msuserauth:
    image: emerlopes95/ms-userauth
    container_name: ms-userauth
    ports:
      - "8081:8081"
    networks:
      - bridge-ecommerce

  msbffecommerce:
    image: emerlopes95/bff-ecommerce
    container_name: ms-bffecommerce
    ports:
      - "8080:8080"
    networks:
      - bridge-ecommerce

networks:
  rede:
    driver: bridge-ecommerce
