version: '3.8'

services:

  ordermanagement:
    image: emerlopes95/payment:latest
    container_name: payment
    ports:
      - "8084:8084"
    networks:
      - rede

  shoppingcart:
    image: emerlopes95/shoppingcart:latest
    container_name: shoppingcart
    ports:
      - "8083:8083"
    networks:
      - rede

  itemmanagement:
    image: emerlopes95/itemmanagement:latest
    container_name: itemmanagement
    ports:
      - "8082:8082"
    networks:
      - rede

  customerauthentication:
    image: emerlopes95/customerauthentication:latest
    container_name: customerauthentication
    ports:
      - "8081:8081"
    networks:
      - rede

  msbffecommerce:
    image: emerlopes95/bffecommerce:latest
    container_name: bffecommerce
    ports:
      - "8080:8080"
    networks:
      - rede

networks:
  rede:
    driver: bridge
