version: '3.8'

services:
  msitem:
    image: emerlopes95/itemmanagement
    container_name: itemmanagement
    ports:
      - "8082:8082"
    networks:
      - bridge-ecommerce

  msuserauth:
    image: emerlopes95/customerauthentication
    container_name: customerauthentication
    ports:
      - "8081:8081"
    networks:
      - bridge-ecommerce

  msbffecommerce:
    image: emerlopes95/bffecommerce
    container_name: bffecommerce
    ports:
      - "8080:8080"
    networks:
      - bridge-ecommerce

networks:
  rede:
    driver: bridge-ecommerce
